#!/bin/bash
# Bootstrap the full local AskWRI stack: docker Postgres (pgvector) + MinIO,
# schema migrations, 169-doc corpus (from the warm cache — no OpenAI cost),
# sparse keyword backfill, MinIO bucket seed, admin user.
#
# Idempotent: every step checks state first. Safe to re-run after a reboot,
# docker wipe, or in a fresh worktree. Never touches .env / search-service/.env
# (deploy-day files); writes the gitignored .env.local, .env.test.local, and
# search-service/.env.local ONLY if they don't already exist.
#
# Usage:  ./scripts/local-bootstrap.sh
# Docs:   docs/runbooks/local-testing.md   (humans)
#         CLAUDE.md "Local development"    (agents)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SS="$REPO_ROOT/search-service"
DATA="$SS/data"
COMPOSE="docker compose -f $REPO_ROOT/docker-compose.local.yml"
psql_local() { docker exec askwri-pg psql -U askwri -d qa -tAc "$1"; }

step() { printf '\n\033[1m== %s ==\033[0m\n' "$*"; }
fail() { printf '\033[31mFAIL: %s\033[0m\n' "$*" >&2; exit 1; }

step "Preflight"
command -v docker >/dev/null || fail "docker not installed / not on PATH"
[ -x "$SS/venv/bin/python" ] || fail "search-service/venv missing — see docs/runbooks/phase0-cutover.md"
pdf_count=$(find "$DATA" -maxdepth 1 -name '*.pdf' 2>/dev/null | wc -l | tr -d ' ')
[ "$pdf_count" -eq 169 ] || fail "corpus incomplete: $pdf_count/169 PDFs in search-service/data — restore before bootstrapping"
[ -f "$DATA/documents.csv" ] || fail "search-service/data/documents.csv missing"
[ -d "$DATA/cache" ] || fail "warm cache missing (search-service/data/cache) — migration would re-embed ~30k chunks (~\$1); restore the cache or delete this check deliberately"
echo "corpus OK: 169 PDFs + documents.csv + warm cache"

step "Symlink /tmp/askWRI_docs -> search-service/data"
if [ ! -e /tmp/askWRI_docs ] && [ ! -L /tmp/askWRI_docs ]; then
  ln -s "$DATA" /tmp/askWRI_docs && echo "created"
elif [ "$(readlink /tmp/askWRI_docs 2>/dev/null)" = "$DATA" ]; then
  echo "already correct"
else
  fail "/tmp/askWRI_docs exists but is not a symlink to $DATA — inspect and remove it manually, then re-run"
fi

step "Containers (postgres :5432, minio :9000/:9001)"
$COMPOSE up -d --wait || fail "containers unhealthy — run '$COMPOSE ps'; check for port conflicts on 5432/9000/9001"
psql_local "SELECT 1" >/dev/null || fail "postgres container not answering"

step "Env files (created only if absent — your edits are never overwritten)"
if [ -f "$REPO_ROOT/.env.local" ]; then echo ".env.local exists — keeping"; else
cat > "$REPO_ROOT/.env.local" <<'EOF'
# Local-dev overrides (gitignored; generated by scripts/local-bootstrap.sh).
# Loaded by: Next.js dev/prod (NOT test — see .env.test.local) and
# scripts/load-env.js (typeorm/seed CLIs). Precedence: real env > .env.local > .env
DB_HOST=localhost
DB_PORT=5432
DB_USER=askwri
DB_PASSWORD=password
DB_NAME=qa
DATABASE_SSL=false
SESSION_SECRET=local-dev-session-secret-0123456789abcdef
CATALOG_SOURCE=postgres
SEARCH_SERVICE_URL=http://127.0.0.1:8000
# S3 -> local MinIO (docker-compose.local.yml). Console: http://localhost:9001
AWS_ENDPOINT_URL=http://localhost:9000
AWS_ACCESS_KEY_ID=local-askwri
AWS_SECRET_ACCESS_KEY=local-askwri-secret
AWS_REGION=us-east-2
DOCUMENTS_S3_BUCKET=askwri-data
DOCUMENTS_S3_PREFIX=
EOF
echo ".env.local written"; fi

if [ -f "$REPO_ROOT/.env.test.local" ]; then echo ".env.test.local exists — keeping"; else
cat > "$REPO_ROOT/.env.test.local" <<'EOF'
# Jest env (gitignored; generated by scripts/local-bootstrap.sh).
# next/jest runs with NODE_ENV=test and Next.js SKIPS .env.local in test mode,
# so the DB-backed *.db.test suites read this file instead.
DATABASE_URL=postgresql://askwri:password@localhost:5432/qa
DB_HOST=localhost
DB_PORT=5432
DB_USER=askwri
DB_PASSWORD=password
DB_NAME=qa
DATABASE_SSL=false
SESSION_SECRET=local-dev-session-secret-0123456789abcdef
EOF
echo ".env.test.local written"; fi

if [ -f "$SS/.env.local" ]; then echo "search-service/.env.local exists — keeping"; else
cat > "$SS/.env.local" <<'EOF'
# Local-dev overrides (gitignored; generated by scripts/local-bootstrap.sh).
# Loaded by: pydantic Settings (app/config.py env_file tuple) AND app/env.py
# into os.environ (app.main, worker.main, tests/conftest — boto3 reads the
# process env, never Settings). Precedence: real env > .env.local > .env
DATABASE_URL=postgresql://askwri:password@localhost:5432/qa
RETRIEVAL_BACKEND=postgres
KEYWORD_BACKEND=sparse
REQUIRE_DB_TESTS=1
# S3 -> local MinIO (docker-compose.local.yml)
AWS_ENDPOINT_URL=http://localhost:9000
AWS_ACCESS_KEY_ID=local-askwri
AWS_SECRET_ACCESS_KEY=local-askwri-secret
AWS_REGION=us-east-2
DOCUMENTS_S3_BUCKET=askwri-data
# DOCUMENTS_S3_PREFIX stays at its 'documents/' default: the worker records the
# same prefix it copies published PDFs to as s3_key, so any value is
# self-consistent. Migrated docs have bare-filename s3_keys seeded by bootstrap.
# INTAKE_LOCAL_DIR intentionally NOT set: the worker must exercise the S3
# (MinIO) intake path — setting it silently switches to the local-dir path.
EOF
echo "search-service/.env.local written"; fi

step "Schema migrations"
(cd "$REPO_ROOT" && npm run migration:run)

step "Corpus -> Postgres (warm cache; skipped when already loaded)"
docs=$(psql_local "SELECT count(*) FROM documents" || echo 0)
if [ "${docs:-0}" -ge 169 ]; then
  echo "skip: $docs documents already present"
else
  (cd "$SS" && ./venv/bin/python -m scripts.migrate_csv_to_postgres)
fi

step "Sparse keyword backfill (skipped when stats exist)"
stats=$(psql_local "SELECT count(*) FROM keyword_corpus_stats" || echo 0)
if [ "${stats:-0}" -ge 1 ]; then
  echo "skip: keyword_corpus_stats populated (refresh manually after bulk changes: scripts.build_sparse_keyword)"
else
  (cd "$SS" && ./venv/bin/python -m scripts.build_sparse_keyword)
fi

step "MinIO seed (bucket askwri-data; bare-filename keys matching migrated s3_key)"
docker run --rm --network askwri-local -v "$DATA:/corpus:ro" --entrypoint /bin/sh minio/mc -c "\
  mc alias set local http://askwri-minio:9000 local-askwri local-askwri-secret >/dev/null && \
  mc mb --ignore-existing local/askwri-data && \
  mc mirror --exclude 'cache/*' --exclude 'feedback/*' --exclude 'documents.csv' /corpus local/askwri-data"

step "Admin user (admin / admin-local-password)"
(cd "$REPO_ROOT" && ADMIN_PASSWORD=admin-local-password npm run seed:admin -- admin)

step "Verify"
counts=$(psql_local "SELECT (SELECT count(*) FROM documents) || '/' ||
  (SELECT count(*) FROM documents WHERE status='searchable') || '/' ||
  (SELECT count(*) FROM document_texts) || '/' ||
  (SELECT count(*) FROM document_chunks WHERE embedding IS NULL)")
echo "docs/searchable/texts/missing_embeddings = $counts"
IFS=/ read -r docs searchable texts missing <<<"$counts"
[ "$missing" -eq 0 ]      || fail "$missing chunks missing embeddings — re-run the sparse/embedding backfill"
[ "$docs" -ge 169 ]       || fail "only $docs documents (baseline corpus is 169) — corpus load incomplete"
[ "$texts" -ge 169 ]      || fail "only $texts document_texts rows — text extraction incomplete"
[ "$searchable" -ge 169 ] || fail "only $searchable searchable docs — baseline corpus not fully indexed"
[ "$docs" -eq 169 ] || echo "note: $((docs - 169)) doc(s) above the 169 baseline (worker e2e canaries / drafts) — expected"
echo "corpus verified"
vocab=$(psql_local "SELECT count(*) FROM keyword_vocab" || echo "n/a")
echo "sparse vocab terms: $vocab (expect ~184395)"

cat <<'EOF'

Bootstrap complete. Start the stack (three terminals):

  1. search service :8000   cd search-service && ./venv/bin/python -m app.main
  2. web app        :3000   npm run dev
  3. worker (when needed)   cd search-service && ./venv/bin/python -m worker.main

Health check:  curl -s localhost:8000/health
  expect "status":"healthy", "retrieval_backend":"postgres", "keyword_backend":"sparse"
Admin UI:      http://localhost:3000/admin  (admin / admin-local-password)
MinIO console: http://localhost:9001       (local-askwri / local-askwri-secret)
Full guide:    docs/runbooks/local-testing.md
EOF
